spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: anime-service
          uri: lb://anime-service
          predicates:
            - Path=/api/anime/**
          filters:
            - StripPrefix=2
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/review/**
          filters:
            - StripPrefix=2


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
