spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    gateway:
      routes:
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
